### ISSUE TITLE
Cannot install on Node.js 8

### ISSUE THREAD

**Issue by compwright** [stealjs/steal-react-jsx#11]
```
jhills-MacBook-Pro: jhill$ yarn add steal-jsx
yarn add v1.3.2
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
error steal-jsx@0.0.2: The engine "node" is incompatible with this module. Expected version "4.x - 5.x.x".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by iagobruno** [comment]
Having the same problem here

**Comment by chasenlehara** [comment]
Thanks for reporting guys, this should be fixed in [steal-react-jsx@0.0.4](https://github.com/stealjs/steal-react-jsx/releases/tag/v0.0.4)

**Comment by httpiago** [comment]
It's working for me now

**Comment by iagobruno** [comment]
Works when I use npm, but not with yarn

![image](https://user-images.githubusercontent.com/3616259/41742341-0f4524b8-7574-11e8-92e0-03d4ce5e2c79.png)

**Comment by chasenlehara** [comment]
Oh, that’s confusing. I guess this package was renamed from `steal-jsx` to `steal-react-jsx`? Installing the latter should work.

**Comment by iagobruno** [comment]
The problem with the mismatch was resolved but now another one appeared 😥
Happen an error when I try to build:

![image](https://user-images.githubusercontent.com/3616259/41888226-cb89acac-78da-11e8-8972-ff4422ffe358.png)

And it is with this package even because when I remove the import file (import Title from './title.jsx'), it works normally

![image](https://user-images.githubusercontent.com/3616259/41889110-18fa281e-78df-11e8-9da0-f1e027ca4ef4.png)
